Repository projectcalico/pod2daemon, pull requests merged in 2021-08, with the labels that each got.

#72 Change release repo to docker.io, add RELEASE and CONFIRM env variables
  Makefile
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#73 Automated cherry pick of #72: Change release repo to docker.io, add RELEASE and CONFIRM env
  Makefile
Labels: docs-not-required, release-note-not-required

#64 Fixed typo in umount command
  flexvol/flexvoldriver.go
Labels: release-note-required, docs-not-required, merge-when-ready
